<<<<<<< HEAD
comment:
  layout: header, changes, diff
coverage:
  ignore:
  - base.php
  - helper.php
  - convention.php
  - lang/zh-cn.php
  - start.php
  - console.php
  status:
    patch: false
=======
comment:
  layout: header, changes, diff
coverage:
  ignore:
  - base.php
  - helper.php
  - convention.php
  - lang/zh-cn.php
  - start.php
  - console.php
  status:
    patch: false
>>>>>>> e0e786473fa2c4a6034924ea9b087f8098764833
